/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application_gestion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ibrahim
 */
public class GestionApp extends javax.swing.JFrame {

    private DefaultTableModel dt;
    private int id ,mat ;
    private String nom,prenom,sexe;
    private String  service;
    private String duree;
    
    private int  i; // indicate the movement
    Connection con = null; /* to conecte with datebase*/
    Statement st = null; /*to save sql request */
    ResultSet rs = null; // to save the result ;
    public String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    public String username = "root", password = "YES";
    static String dbname = "jdbc:mysql://localhost:3306/Gestion";
    
    
    /**
     * Creates new form GestionApp
     */
    public GestionApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtmat = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtpre = new javax.swing.JTextField();
        txtdur = new javax.swing.JTextField();
        txtserv = new javax.swing.JComboBox<>();
        jrb1 = new javax.swing.JCheckBox();
        jrb2 = new javax.swing.JCheckBox();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstg = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        comrech = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        btn5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("Mat");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setText("Nom");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel4.setText("Prenom");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setText("Service");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setText("Durée");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel7.setText("Sexe");

        txtid.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtmat.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatActionPerformed(evt);
            }
        });

        txtnom.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });

        txtpre.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreActionPerformed(evt);
            }
        });

        txtdur.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtdur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdurActionPerformed(evt);
            }
        });

        txtserv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "informatique", "Gestion et recrutement", "Maintenance", "Logistique", "Fiscale", "Transport", " " }));

        jrb1.setText("Masculin");
        jrb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb1ActionPerformed(evt);
            }
        });

        jrb2.setText("Féminin");
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });

        btn3.setText("Supprimer");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setText("Ajouter");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("Modifier");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn4.setText("Actualiser");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        tblstg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblstg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstg);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel8.setText("Recherche par:");

        comrech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Mat", "Nom", "Prénom", "Service", "Durée", "Sexe" }));

        jTextField7.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        btn5.setText("Rechercher");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("URW Chancery L", 3, 36)); // NOI18N
        jLabel9.setText("                       Application de Gestion des Stagaires");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(txtmat)
                                        .addComponent(txtnom)
                                        .addComponent(txtpre)
                                        .addComponent(txtdur)
                                        .addComponent(txtserv, 0, 0, Short.MAX_VALUE))
                                    .addGap(27, 27, 27)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(48, 48, 48)
                                    .addComponent(jrb1)
                                    .addGap(3, 3, 3)
                                    .addComponent(jrb2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(71, 71, 71)
                                    .addComponent(jLabel8)
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comrech, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(64, 64, 64)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1)
                            .addGap(23, 23, 23)
                            .addComponent(jLabel2)
                            .addGap(23, 23, 23)
                            .addComponent(jLabel3)
                            .addGap(13, 13, 13)
                            .addComponent(jLabel4)
                            .addGap(33, 33, 33)
                            .addComponent(jLabel5)
                            .addGap(23, 23, 23)
                            .addComponent(jLabel6))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(txtmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(txtpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(txtserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)
                            .addComponent(txtdur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jrb1)
                        .addComponent(jrb2))
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel8))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(comrech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 22, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreActionPerformed

    private void txtdurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdurActionPerformed

    private void jrb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb1ActionPerformed
        sexe=jrb1.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jrb1ActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
       sexe=jrb2.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jrb2ActionPerformed

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
        // TODO add your handling code here:
        //btn1.setBackground(new java.awt.Color(102,225,223));
    }//GEN-LAST:event_btn1MouseExited

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
   //     btn1.setBackground(new java.awt.Color(122,22,223));        // TODO add your handling code here:
    }//GEN-LAST:event_btn1MouseEntered

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
        // TODO add your handling code here:
     //   btn2.setBackground(new java.awt.Color(122,22,223));
    }//GEN-LAST:event_btn2MouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    try{
        // connexion avec base de donnée Gestion
        Class.forName(JDBC_DRIVER); // the name of database
        con=DriverManager.getConnection(dbname,username,password);
  
//make connection with my date base
      st = con.createStatement();//where we save our sql request
     
        jrbg.add(jrb1);
        jrbg.add(jrb2);
        
      
        dt = new DefaultTableModel();// dt c'est un variable pour stocké les element d'un tableau {ligne et colomn}
      
        dt.addColumn("id");
        dt.addColumn("matriculation");
        dt.addColumn("nom");
        dt.addColumn("prenom");
        dt.addColumn("service");
        dt.addColumn("duree");
        dt.addColumn("sexe");
        tblstg.setModel(dt);
        // afficehr la liste des stagiaires
        AfficherStagiaire();
        // remplir les champs 
         i = 0;
       DeplacerStagiaire(i);
    }catch(ClassNotFoundException | SQLException e){
        System.out.printf("erreur   "+e.getMessage());//getMessage c'est une fonction  pour afficher l'Erreur ou se trouve ?!!!!!
        JOptionPane.showMessageDialog(null, "Erreur de connexion\n  "+ e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void tblstgMouseClicked(java.awt.event.MouseEvent evt) {                                    
             try{
        i = tblstg.getSelectedRow(); // getSelectedRow() fonction nous retourne le ligne selectionner par l utilisateur
         
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur selectionnéé stg\n"+e.getMessage());
    }
                                    
  // TODO add your handling code here:
    }                                   

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
 
        try{
   
String sql = "INSERT INTO Gestion  (Id,matriculation,nom,prenom,service,duree,sexe)VALUES (?,?,?,?,?,?,?)";
      PreparedStatement ps = con.prepareStatement(sql);
      ps.setString(1, txtid.getText());
      ps.setString(2, txtmat.getText());
      ps.setString(3, txtnom.getText());
      ps.setString(4, txtpre.getText());
      ps.setString(5, txtserv.getSelectedItem().toString());
      ps.setString(6, txtdur.getText());
      ps.setString(7, sexe);     
      ps.executeUpdate();
      AfficherStagiaire(); // recharger la liste des stagiaires
      JOptionPane.showMessageDialog(null,"Stagiaire est ajouté");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur ajouter stg\n"+e.getMessage());
        System.err.println(""+e.getMessage());
    }
       // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
try{ 
        // msg d confirmation !
        if (JOptionPane.showConfirmDialog(null, "confirmer la modification","modification sur un stagaire",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
           st.executeUpdate("UPDATE Gestion SET matriculation='"+txtid.getText()+"',nom='"+txtnom.getText()
      +"',prenom='"+txtpre.getText()+"',service='"+txtserv.getSelectedItem().toString()
                   +"',duree='"+txtdur.getText()+"',sexe='"+sexe
                   +"' WHERE Id = "+ txtid.getText());       
           //lorseque en fait +txtfield.gettext+ en doit ecrit les appostrophe ""
  
           AfficherStagiaire(); // recharger la liste des stagiaires
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur modifier stg\n"+e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
try{
        if(JOptionPane.showConfirmDialog(null, "attention est tu es sure que"
                + " tu veux supprimer ce stagaire","Supprimer stagaire",JOptionPane.YES_NO_OPTION)
                == JOptionPane.OK_OPTION){
   //si textfield id est vide ,on peux pas supprimmer
                st.executeUpdate("Delete from Gestion where Id = "+ txtid.getText());
                AfficherStagiaire(); // recharger la liste des stagiaires ...
           
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur supprimer stg !\n"+e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
try { 
    dt.setRowCount(0); //pour vider tableau 
    Statement st = con.createStatement();
        ResultSet rs = st.executeQuery( "SELECT * FROM Gestion WHERE "+combo()
                +"  like '%"+btn5.getText()+"%'" );
    
     while(rs.next()){
         id=rs.getInt(1);  
         mat = rs.getInt("mat"); // la même chose
         nom = rs.getString(3);
         prenom = rs.getString(4);
         service = rs.getString(5);
         duree = rs.getString(6);
         sexe=rs.getString(7);
            
            Object[] stg = {id,mat,nom,prenom,service,duree,sexe};
            dt.addRow(stg);
        }
     
        if (dt.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Aucun Stagiaire");
            AfficherStagiaire(); // afficehr tout les stgs
        }else{
            i = 0;
            DeplacerStagiaire(i);
        }
    
}catch (Exception m){JOptionPane.showMessageDialog(null, ""+m.getMessage());
System.err.println(m);}        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed
    
    private void btn2MouseExited(java.awt.event.MouseEvent evt){
         btn2.setBackground(new java.awt.Color(102,225,223));
    } 
    private void btn3MouseExited(java.awt.event.MouseEvent evt){
        btn3.setBackground(new java.awt.Color(102,225,223));
    }
    private void btn3MouseEntered(java.awt.event.MouseEvent evt){
          btn3.setBackground(new java.awt.Color(122,22,223));
    }
     private void btn4MouseExited(java.awt.event.MouseEvent evt){
        btn4.setBackground(new java.awt.Color(102,225,223));
    }
    private void btn4MouseEntered(java.awt.event.MouseEvent evt){
          btn4.setBackground(new java.awt.Color(122,22,223));
    }
    private void AfficherStagiaire(){
  
   //txtid.setEnabled(false);
   
     try{
        dt.setRowCount(0); // vider la list des stagiaires.
        rs = st.executeQuery("Select * From Gestion");//it's a method in statment to get information
        
        while(rs.next()){
            id=rs.getInt("Id");
            mat = rs.getInt("matriculation");
            nom = rs.getString("nom");
            prenom = rs.getString("prenom");
            service = rs.getString("service");
            duree = rs.getString("duree");
            sexe = rs.getString("sexe");
            Object[] stg = {id,mat,nom,prenom,service,duree,sexe};
            dt.addRow(stg);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur afficher la liste des stagiaire\n"+e.getMessage());
    }
    

}
        
    private void DeplacerStagiaire(int i){
    try{
       
        txtid.setText(dt.getValueAt(i, 0).toString()); 
        txtmat.setText(dt.getValueAt(i, 1).toString()); // i represente numero d ligne ,et 0 1 .. colonne
        txtnom.setText(dt.getValueAt(i, 2).toString()); // lorseque i=1 getValueAt nous retourne le premier ligne si i=2 le ligne ......
        txtpre.setText(dt.getValueAt(i, 3).toString());
        txtserv.setSelectedItem(dt.getValueAt(i, 4).toString());
        txtdur.setText(dt.getValueAt(i, 5).toString());
        String s = dt.getValueAt(i, 6).toString();
        if(s.equals("Masculin")){jrb1.setSelected(true);}else if(s.equals("Féminin")){jrb2.setSelected(true);}
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur deplacement stagiaire\n"+e.getMessage());
    }
}
      String combo(){
switch(comrech.getSelectedIndex()){ 
        case 0: return "id"; 
        case 1: return "mat";
        case 2: return "nom";
        case 3: return "prenom";
        case 4: return "service";
        case 5: return "dure";
        case 6: return "sexe";
      }
      return "";
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GestionApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JComboBox<String> comrech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JCheckBox jrb1;
    private javax.swing.JCheckBox jrb2;
    private javax.swing.ButtonGroup jrbg;
    private javax.swing.JTable tblstg;
    private javax.swing.JTextField txtdur;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpre;
    private javax.swing.JComboBox<String> txtserv;
    // End of variables declaration//GEN-END:variables
}
